sudo: required

services:
- docker

language: java
jdk: openjdk11

env:
  global:
  - IMAGE_NAME="$DOCKER_GCP_LOCATION/ssdc-rm-caseprocessor"

before_install:
  - mvn fmt:check

script: mvn -DskipITs -DdockerCompose.skip verify jacoco:report

cache:
  directories:
  - $HOME/.m2

branches:
  only:
  - main
