steps:
  - name: maven
    entrypoint: mvn
    args: [ '--version' ]
  - name: maven
    entrypoint: mvn
    args: [ 'fmt:check','pmd:check' ]
    id: mvn format
  - id: docker-network
    name: 'docker'
    args: [ 'network', 'create' ,'ssdcrmdockerdev_default']
    waitFor: [ '-' ]
  - id: docker-compose
    name: 'docker/compose:1.19.0'
    args: ['-f', '/workspace/src/test/resources/docker-compose.yml', 'up', '-d']
    waitFor: ['docker-network']
  - name: maven
    entrypoint: mvn
    args: [ 'verify','jacoco:report', '-DdockerCompose.skip=true' ]
    waitFor: ['docker-compose', 'mvn-format']
#  - name: bash
#    args: ["./check_codecov.sh"]