steps:
  - name: maven
    entrypoint: mvn
    args: [ '--version' ]
  - name: docker
    args: ['compose', '--help']
    waitFor: ['-']
  - name: maven
    entrypoint: mvn
    args: [ 'fmt:check','pmd:check' ]
  - name: maven
    entrypoint: mvn
    args: [ 'verify','jacoco:report' ]
#  - name: bash
#    args: ["./check_codecov.sh"]