steps:
  - name: maven
    entrypoint: mvn
    args: [ 'fmt:check','pmd:check' ]
    id: mvn-format
  - id: docker-compose
    name: 'docker/compose:1.29.0'
    args: ['-f', '/workspace/src/test/resources/docker-compose-ci.yml', 'up', '-d']
  - name: maven:3.8.3-openjdk-17-slim
    entrypoint: mvn
    args: [ 'verify','jacoco:report', '-DdockerCompose.skip=true', '-Dspring.profiles.active=test-ci' ]
  - name: gcr.io/cloud-builders/curl
    entrypoint: bash
    args:
      - 'ls'
      - './codecov_checks.sh'