steps:
  - name: maven:3-jdk-17
    entrypoint: mvn
    args: [ '--version' ]
  - name: maven:3-jdk-17
    entrypoint: mvn
    args: [ 'fmt:check','pmd:check' ]
#  - name: maven:3-jdk-17
#    entrypoint: mvn
#    args: [ 'verify','jacoco:report' ]
#  - name: bash
#    args: ["./check_codecov.sh"]