spring:
  task:
    scheduling:
      pool:
        size: 10

  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximumPoolSize: 50

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: casev3
        jdbc:
          lob:
            non_contextual_creation: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  telephone-capture-queue: caseApi.caseProcessor.telephoneCapture
  sample-queue: case.sample.inbound
  receipt-response-queue: Case.Responses
  refusal-response-queue: case.refusals
  print-queue: Action.Printer
  invalid-address-queue: case.invalidaddress
  survey-launched-queue: survey.launched
  fulfilment-queue: events.caseProcessor.fulfilment
  case-event-exchange: events
  consumers: 50
  retry-attempts: 3
  retry-delay: 1000 #milliseconds

healthcheck:
  frequency: 15000 #milliseconds
  filename: /tmp/case-processor-healthy

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666

messagelogging:
  logstacktraces: false

logging:
  level:
    org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler: ERROR

caserefgeneratorkey: abc123

scheduler:
  frequency: 1000 #milliseconds
  chunksize: 1000
  leaderDeathTimeout: 120 #seconds

uacservice:
  connection:
    scheme: http
    host: localhost
    port: 8164

  uacqid-cache-min: 500
  uacqid-fetch-count: 1000
  uacqid-get-timeout: 60   #seconds
