spring:
  task:
    scheduling:
      pool:
        size: 30

  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 50

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: casev3
        jdbc:
          batch_size: 1000
          order_inserts: true
          lob:
            non_contextual_creation: true

  cloud:
    gcp:
      pubsub:
        subscriber:
          flow-control:
            max-outstanding-element-count: 100

queueconfig:
  telephone-capture-subscription: rm-internal-telephone-capture_case-processor
  sms-fulfilment-subscription: rm-internal-sms-fulfilment_case-processor
  email-fulfilment-subscription: rm-internal-email-fulfilment_case-processor
  new-case-subscription: event_new-case_rm-case-processor
  receipt-subscription: event_receipt_rm-case-processor
  refusal-subscription: event_refusal_rm-case-processor
  invalid-case-subscription: event_invalid-case_rm-case-processor
  eq-launch-subscription: event_eq-launch_rm-case-processor
  uac-authentication-subscription: event_uac-authentication_rm-case-processor
  print-fulfilment-subscription: event_print-fulfilment_rm-case-processor
  deactivate-uac-subscription: event_deactivate-uac_rm-case-processor
  update-sample-subscription: event_update-sample_rm-case-processor
  update-sample-sensitive-subscription: event_update-sample-sensitive_rm-case-processor
  sms-request-topic: rm-internal-sms-request
  email-request-topic: rm-internal-email-request
  case-update-topic: event_case-update
  uac-update-topic: event_uac-update
  deactivate-uac-topic: event_deactivate-uac
  publishtimeout: 30  # In seconds
  shared-pubsub-project: REPLACEME

healthcheck:
  frequency: 15000 #milliseconds
  filename: /tmp/case-processor-healthy

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666

messagelogging:
  logstacktraces: false

logging:
  profile: DEV
  level:
    root: INFO

caserefgeneratorkey: abc123

scheduler:
  frequency: 1000 #milliseconds
  chunksize: 1000
  leaderDeathTimeout: 120 #seconds

uacservice:
  connection:
    scheme: http
    host: localhost
    port: 8164

  uacqid-cache-min: 500
  uacqid-fetch-count: 1000
  uacqid-get-timeout: 60   #seconds
