spring:
  task:
    scheduling:
      pool:
        size: 10

  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 50

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: casev3
        jdbc:
          lob:
            non_contextual_creation: true

  cloud:
    gcp:
      pubsub:
        emulator-host: localhost:18538
        project-id: project


queueconfig:
  telephone-capture-subscription: rm-internal-telephone-capture_case-processor
  sample-subscription: rm-internal-sample_case-processor
  receipt-response-subscription: event_receipt_rm-case-processor
  refusal-response-subscription: event_refusal_rm-case-processor
  print-topic: rm-internal-print-row
  invalid-address-subscription: event_invalid_rm-case-processor
  survey-launched-subscription: event_survey-launched_rm-case-processor
  fulfilment-subscription: event_paper-fulfilment_rm-case-processor
  deactivate-uac-subscription: event_deactivate-uac_rm-case-processor
  update-sample-sensitive-subscription: event_update-sample-sensitive_rm-case-processor
  case-update-topic: event_case-update
  uac-update-topic: event_uac-update
  deactivate-uac-topic: event_deactivate-uac
  publishtimeout: 30  # In seconds

healthcheck:
  frequency: 15000 #milliseconds
  filename: /tmp/case-processor-healthy

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666

messagelogging:
  logstacktraces: false

logging:
  level:
    org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler: ERROR

caserefgeneratorkey: abc123

scheduler:
  frequency: 1000 #milliseconds
  chunksize: 1000
  leaderDeathTimeout: 120 #seconds

uacservice:
  connection:
    scheme: http
    host: localhost
    port: 8164

  uacqid-cache-min: 500
  uacqid-fetch-count: 1000
  uacqid-get-timeout: 60   #seconds
