spring:
  task:
    scheduling:
      pool:
        size: 10

  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 50

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: casev3
        jdbc:
          lob:
            non_contextual_creation: true

  cloud:
    gcp:
      pubsub:
        emulator-host: localhost:8538
        project-id: project


queueconfig:
  telephone-capture-subscription: caseApi.caseProcessor.telephoneCapture.subscription
  sample-subscription: supportTool.caseProcessor.sample.subscription
  receipt-response-subscription: events.caseProcessor.response.subscription
  refusal-response-subscription: events.caseProcessor.refusal.subscription
  print-topic: caseProcessor.printFileSvc.printBatchRow.topic
  invalid-address-subscription: events.caseProcessor.invalidAddress.subscription
  survey-launched-subscription: events.caseProcessor.surveyLaunched.subscription
  fulfilment-subscription: events.caseProcessor.fulfilment.subscription
  deactivate-uac-subscription: events.caseProcessor.deactivateUac.subscription
  update-sample-sensitive-subscription: events.caseProcessor.updateSampleSensitive.subscription
  case-update-topic: events.caseUpdate.topic
  uac-update-topic: events.uacUpdate.topic
  deactivate-uac-topic: events.deactivateUac.topic

healthcheck:
  frequency: 15000 #milliseconds
  filename: /tmp/case-processor-healthy

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666

messagelogging:
  logstacktraces: false

logging:
  level:
    org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler: ERROR

caserefgeneratorkey: abc123

scheduler:
  frequency: 1000 #milliseconds
  chunksize: 1000
  leaderDeathTimeout: 120 #seconds

uacservice:
  connection:
    scheme: http
    host: localhost
    port: 8164

  uacqid-cache-min: 500
  uacqid-fetch-count: 1000
  uacqid-get-timeout: 60   #seconds
