[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "caseprocessor"
version = "0.9.7"
description = "Caseprocessor"
urls = { "Homepage" = "https://github.com/ONSdigital/ssdc-rm-caseprocessor" }

[tool.setuptools]
packages = { find = {} }