[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "caseprocessor"
version = "0.0.1"

[tool.setuptools]
packages= ["caseprocessor*"]
py-modules = []