package uk.gov.ons.ssdc.caseprocessor.model.dto;

public enum EventTypeDTO {
  CASE_CREATED,
  CASE_UPDATED,
  UAC_UPDATED,
  RESPONSE_RECEIVED,
  REFUSAL_RECEIVED,
  SAMPLE_LOADED,
  ADDRESS_NOT_VALID,
  SURVEY_LAUNCHED,
  RESPONDENT_AUTHENTICATED,
  FULFILMENT,
  TELEPHONE_CAPTURE_REQUESTED,
  DEACTIVATE_UAC,
  UPDATE_SAMPLE_SENSITIVE
}
