package uk.gov.ons.ssdc.caseprocessor.model.dto;

public enum EventTypeDTO {
  NEW_CASE,
  CASE_UPDATE,
  UAC_UPDATE,
  RECEIPT,
  REFUSAL,
  INVALID_CASE,
  SURVEY_LAUNCH,
  UAC_AUTHENTICATION,
  PRINT_FULFILMENT,
  TELEPHONE_CAPTURE,
  DEACTIVATE_UAC,
  UPDATE_SAMPLE_SENSITIVE
}
